# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 275)
        MainWindow.setMinimumSize(QtCore.QSize(507, 275))
        MainWindow.setMaximumSize(QtCore.QSize(507, 275))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSubmit.setGeometry(QtCore.QRect(70, 190, 93, 28))
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.buttonExit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonExit.setGeometry(QtCore.QRect(350, 190, 93, 28))
        self.buttonExit.setObjectName("buttonExit")
        self.buttonClear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(210, 190, 93, 28))
        self.buttonClear.setObjectName("buttonClear")
        self.entryISBN = QtWidgets.QLineEdit(self.centralwidget)
        self.entryISBN.setGeometry(QtCore.QRect(150, 40, 131, 22))
        self.entryISBN.setObjectName("entryISBN")
        self.entryAuthor = QtWidgets.QLineEdit(self.centralwidget)
        self.entryAuthor.setGeometry(QtCore.QRect(150, 90, 131, 22))
        self.entryAuthor.setObjectName("entryAuthor")
        self.entryTitle = QtWidgets.QLineEdit(self.centralwidget)
        self.entryTitle.setGeometry(QtCore.QRect(150, 140, 131, 22))
        self.entryTitle.setObjectName("entryTitle")
        self.labelISBN = QtWidgets.QLabel(self.centralwidget)
        self.labelISBN.setGeometry(QtCore.QRect(50, 40, 81, 21))
        self.labelISBN.setObjectName("labelISBN")
        self.labelAuthor = QtWidgets.QLabel(self.centralwidget)
        self.labelAuthor.setGeometry(QtCore.QRect(50, 90, 81, 21))
        self.labelAuthor.setObjectName("labelAuthor")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(50, 140, 81, 21))
        self.labelTitle.setObjectName("labelTitle")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(290, 40, 171, 121))
        self.output.setText("")
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Book Inventory"))
        self.buttonSubmit.setText(_translate("MainWindow", "Submit"))
        self.buttonExit.setText(_translate("MainWindow", "Exit"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.labelISBN.setText(_translate("MainWindow", "ISBN"))
        self.labelAuthor.setText(_translate("MainWindow", "Author"))
        self.labelTitle.setText(_translate("MainWindow", "Title"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
